apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: v1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: sample-app-prod
        app.kubernetes.io/name: sample-app
        app.kubernetes.io/version: v1.0.0
        cluster.x-k8s.io/cluster-name: demo-cluster-name
    spec:
      containers: []
      dnsPolicy: ClusterFirst
