apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleappprod
  namespace: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: sampleapp-prod
      app.kubernetes.io/name: sampleapp
      cluster.x-k8s.io/cluster-name: demo-cluster-name
  template:
    metadata:
      labels:
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: sampleapp-prod
        app.kubernetes.io/name: sampleapp
        cluster.x-k8s.io/cluster-name: demo-cluster-name
    spec:
      containers:
        - env:
            - name: APP_NAME
              value: sampleapp
            - name: ENVIRONMENT
              value: prod
            - name: INSTANCE
              value: sampleapp-prod
            - name: CLUSTER
              value: demo-cluster-name
          image: gcr.io/google-samples/gb-frontend:v4
          name: main
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: 30Gi
              memory: 2Gi
            requests:
              cpu: "1"
              ephemeral-storage: 30Gi
              memory: 1Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: sampleapp
