apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: sample-app-prod
      cluster.x-k8s.io/cluster-name: demo-cluster-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-app
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: sample-app-prod
        cluster.x-k8s.io/cluster-name: demo-cluster-name
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: sample-app
        - name: ENVIRONMENT
          value: prod
        - name: INSTANCE
          value: sample-app-prod
        - name: CLUSTER
          value: demo-cluster-name
        image: gcr.io/google-samples/gb-frontend:v4
        name: main
        volumeMounts:
        - mountPath: /home/admin/logs
          name: log-volume
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
            ephemeral-storage: 35Gi
          requests:
            cpu: '2'
            memory: 4Gi
            ephemeral-storage: 35Gi
      dnsPolicy: ClusterFirst
      volumes:
      - name: log-volume
        emptyDir: {}
