apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontendprod
  namespace: guestbook-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: guestbook-frontend-prod
      app.kubernetes.io/name: guestbook-frontend
      cluster.x-k8s.io/cluster-name: demo-cluster-name
      tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: guestbook-frontend-prod
        app.kubernetes.io/name: guestbook-frontend
        cluster.x-k8s.io/cluster-name: demo-cluster-name
        tier: frontend
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: APP_NAME
              value: guestbook-frontend
            - name: ENVIRONMENT
              value: prod
            - name: INSTANCE
              value: guestbook-frontend-prod
            - name: CLUSTER
              value: demo-cluster-name
          image: gcr.io/google-samples/gb-frontend:v4
          name: php-redis
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: 35Gi
              memory: 4Gi
            requests:
              cpu: "2"
              ephemeral-storage: 35Gi
              memory: 4Gi
      dnsPolicy: ClusterFirst
